### ISSUE TITLE
NullPointerException, Spring Boot project.

### ISSUE THREAD

**Issue by linight** [TravaOpenJDK/trava-jdk-11-dcevm#20]
Hello. I can not start project with DCEVM 11.0.1+8, Spring Boot version: 5.1.8-RELEASE. Stack trace: 
```
o.s.boot.SpringApplication - Application run failed
java.lang.NullPointerException: null
	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.tryObjenesisProxyCreation(EnhancerProxyCreater.java:231)
	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.buildProxyCreaterClass(EnhancerProxyCreater.java:208)
	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.getProxyCreationMethod(EnhancerProxyCreater.java:149)
	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.doCreate(EnhancerProxyCreater.java:124)
	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.create(EnhancerProxyCreater.java:97)
	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.createProxy(EnhancerProxyCreater.java:93)
	at org.hotswap.agent.plugin.spring.getbean.ProxyReplacer.register(ProxyReplacer.java:103)
	at spring.beans@5.1.8.RELEASE/org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java)
	at spring.context@5.1.8.RELEASE/org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:179)
	at spring.context@5.1.8.RELEASE/org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
	at spring.context@5.1.8.RELEASE/org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
	at spring.boot@2.1.6.RELEASE/org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at spring.boot@2.1.6.RELEASE/org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
	at spring.boot@2.1.6.RELEASE/org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
	at spring.boot@2.1.6.RELEASE/org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at spring.boot@2.1.6.RELEASE/org.springframework.boot.SpringApplication.run(SpringApplication.java:1213)
	at spring.boot@2.1.6.RELEASE/org.springframework.boot.SpringApplication.run(SpringApplication.java:1202)
	at me.artsense.server/me.artsense.server.Application.main(Application.java:52)
```

**Comment by skybber** [comment]
Hi, please move it to [HotswapAgent](https://github.com/HotswapProjects/HotswapAgent), since it is HA problem. Thanks.
